### ISSUE TITLE
Logout response sent to ACS instead of SLS

### ISSUE THREAD

**Issue by chandon** [capriza/samling#16]
When initiating a SLO from my SP, the response sent by Samling is sent to AssertionConsumerService Location instead of SingleLogoutService Location (my SP metadata contains 2 differents locations)

**Comment by fujifish** [comment]
That's because Samling is an ad-hoc IDP - there is no SP metadata exchange phase, so there is no way for Samling to know the Logout Service Endpoint in advance.

I can suggest the following:
1. Add the `manual=true` query parameter to the logout request url sent to Samling. This will prevent samling from automatically submitting the form with the logout response.
2. before manually submitting the LogoutResponse in Samling, switch over to the `SAML Response Properties` tab, and change the `Assertion Consumer URL` to your LogoutService endpoint. 
Samling will send the LogoutResponse to the url you specify.

**Comment by chandon** [comment]
@fujifish thanks for the suggestion.

As my SLS only accept HTTP-Redirect, i managed to do it by :
1) setting manual=true
2) copying the XML response from the SAMLResponse
3) changing the ACS url in the xml response to SLS url (and disabling the response signature check on my SP)
4) base64encode, urlencode then adding ?SAMLResponse=XXX to my SLS endpoint
